In [1]:
import tensorflow as tf

In [2]:
# rank-1 tensor
vec1 = tf.constant([1, 0])
vec2 = tf.constant([-1, 2])

In [3]:
mat1 = tf.stack([vec1, vec2])
tf.rank(mat1)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [4]:
# get sum
int(tf.reduce_sum(mat1))

2

In [5]:
mat = tf.constant([[0, 1, 2, 3],
                   [4, 5, 6, 7]])
print(mat.shape[0])
print(mat.shape[1])

2
4


In [6]:
# slicing 
mat[0, 1:3]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [7]:
tensor = tf.constant([i for i in range(0, 48) if i % 2 == 0])
print(tensor)
tensor1 = tf.reshape(tensor, [2, 3, 4])
print(tensor1)

tf.Tensor([ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46], shape=(24,), dtype=int32)
tf.Tensor(
[[[ 0  2  4  6]
  [ 8 10 12 14]
  [16 18 20 22]]

 [[24 26 28 30]
  [32 34 36 38]
  [40 42 44 46]]], shape=(2, 3, 4), dtype=int32)


In [17]:
# tf variable
# tf variable can be calculated as same as tensor, using value of stored tensor
tensor1 = tf.constant(range(0,4))

tensor_var1 = tf.Variable(tensor1)


print(tensor_var1)
tensor_var1.assign([1, 2],
                    [3, 4])

tensor2 = tf.convert_to_tensor(tensor_var1)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>
<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>


ValueError: Cannot assign to variable Variable:0 due to variable shape (4,) and value shape (2, 2) are incompatible